name: scVelo
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip=3.23.2.1
  - pip:
      anndata==0.11.3
      array_api_compat==1.10.0
      click==8.1.8
      colorama==0.4.6
      contourpy==1.3.1
      cycler==0.12.1
      filelock==3.16.1
      fonttools==4.55.0
      fsspec==2024.10.0
      h5py==3.13.0
      Jinja2==3.1.4
      joblib==1.4.2
      kiwisolver==1.4.7
      legacy-api-wrap==1.4.1
      llvmlite==0.43.0
      loompy==3.0.8
      MarkupSafe==3.0.2
      matplotlib==3.9.2
      mpmath==1.3.0
      natsort==8.4.0
      networkx==3.4.2
      numba==0.60.0
      numpy==2.0.2
      numpy-groupies==0.11.2
      packaging==24.2
      pandas==2.2.3
      patsy==1.0.1
      pillow==11.0.0
      pynndescent==0.5.13
      pyparsing==3.2.0
      python-dateutil==2.9.0.post0
      pytz==2024.2
      scanpy==1.11.0
      scikit-learn==1.5.2
      scipy==1.14.1
      scvelo==0.3.3
      sdeint==0.3.0
      seaborn==0.13.2
      session-info2==0.1.2
      setuptools==75.6.0
      six==1.16.0
      statsmodels==0.14.4
      sympy==1.13.1
      threadpoolctl==3.5.0
      torch==2.5.1
      tqdm==4.67.1
      typing_extensions==4.12.2
      tzdata==2024.2
      umap-learn==0.5.7